--------------------------------------------------------
--  File created - Monday-November-09-2020   
--------------------------------------------------------
REM INSERTING into YAKOV.LICENSE
SET DEFINE OFF;
Insert into YAKOV.LICENSE (LICENSE_NO,DRIVER_SSN,LICENSE_TYPE,LICENSE_CLASS,LICENSE_EXPIRY,ISSUE_DATE,BRANCH_ID) values (1,11111111,'D',5,to_date('24-MAY-22','DD-MON-RR'),to_date('25-MAY-17','DD-MON-RR'),20);
Insert into YAKOV.LICENSE (LICENSE_NO,DRIVER_SSN,LICENSE_TYPE,LICENSE_CLASS,LICENSE_EXPIRY,ISSUE_DATE,BRANCH_ID) values (2,22222222,'D',5,to_date('29-AUG-23','DD-MON-RR'),to_date('29-AUG-16','DD-MON-RR'),40);
Insert into YAKOV.LICENSE (LICENSE_NO,DRIVER_SSN,LICENSE_TYPE,LICENSE_CLASS,LICENSE_EXPIRY,ISSUE_DATE,BRANCH_ID) values (3,33333333,'L',5,to_date('27-DEC-22','DD-MON-RR'),to_date('27-JUN-17','DD-MON-RR'),20);
Insert into YAKOV.LICENSE (LICENSE_NO,DRIVER_SSN,LICENSE_TYPE,LICENSE_CLASS,LICENSE_EXPIRY,ISSUE_DATE,BRANCH_ID) values (4,44444444,'D',5,to_date('30-AUG-22','DD-MON-RR'),to_date('30-AUG-17','DD-MON-RR'),40);
