

ALTER USER test1 IDENTIFIED BY  "Password123!@#"
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;


SHOW PARAMETER SEC_CASE_SENSITIVE_LOGON;

ALTER SYSTEM SET SEC_CASE_SENSITIVE_LOGON = FALSE scope =both;
alter session set current_schema=TEST
select * from test

select * from ALL_USERS;
 
-- USER SQL
create USER test2
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP"
ACCOUNT UNLOCK ;

-- QUOTAS
ALTER USER test2 QUOTA UNLIMITED ON "USERS";

-- ROLES
ALTER USER test2 DEFAULT ROLE "CONNECT";